# .goreleaser.yml
# Build customization
builds:
  - binary: warpwallet
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
brew:
  github:
    owner: moncho
    name: homebrew-warpwallet
  folder: Formula
  homepage:  http://github.com/moncho/warpwallet
  description: A deterministic bitcoin address generator 
  test: |
    system "#{bin}/warpwallet"
